services:
  certigen:
    image: ${IMAGE_NAME:-ghcr.io/jrafaelca/certigen:latest}
    pull_policy: always
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT:-3000}
      APP_HOST: ${APP_HOST:-0.0.0.0}
      DATA_DIR: ${DATA_DIR:-/data}
      APP_NAME: ${APP_NAME:-Certigen}
      APP_VERSION: ${APP_VERSION:-1.0.0}
    volumes:
      - ./data:/data
    restart: unless-stopped
