services:
  certigen:
    image: ghcr.io/jrafaelca/certigen:latest
    container_name: certigen
    restart: unless-stopped
    env_file: .env
    ports:
      - "${FORWARD_PORT:-3000}:3000"
    volumes:
      - ./data:/data
